### PR TITLE
Secure autoconfiguration

### PR DESCRIPTION
**Pull request by u451f**
Hi,

Torbirdy disables Thunderbird's autoconfig wizard by default, and in order not to lose Torbirdy's secure options, we made some changes for Tails to be able to use the wizard, while still proposing only secure options (this is currently being upstreamed at https://bugzilla.mozilla.org/show_bug.cgi?id=669238 and available in Tails from our own packages).

What these patches do:
* **Use Tor's SOCKSPort for Enigmail's keyserver configuration.** It's not necessarily the case that users have an HTTP proxy running on port 8118, and if they do it may be a non-torified Privoxy instance. Using the Tor SOCKSPort will always work, and be torified.
* **Always disable remote account creation.** When the automatic configuration wizard is enabled we probably want to use *it*, and not the remote account creation feature. If that is something TorBirdys want to make enabled as an option, it should not be baked into this same pref. However, it probably is something TorBirdy should not encourage (at least we in Tails decided to disable it), so always hiding it seems like a good idea. This fixes Tails bug https://labs.riseup.net/code/issues/10464
*  **Do not check for new messages at startup.**

We have created ISO images which implement these changes in Tails if ever you wish to test them yourself. These images can be found here: http://nightly.tails.boum.org/build_Tails_ISO_feature-6154-secure-autoconfig-in-icedove/builds/lastSuccessfulBuild/archive/build-artifacts/

Please let me know if this suits you.

Cheers!
u.

### CODE REVIEW

**Comment by u451f** [comment]
Friendly ping? :)

**Comment by azadi** [comment]
Hi @u451f. Really sorry for not replying or even following up.

I am going to start working on TorBirdy very soon and I promise this is the first patch I will look at!

**Comment by u451f** [comment]
Hi Sukhbir,

do you think you can review this one too these days? That would make a little kitten happy ;) I see the branch has confllcts now. I can try to fix those first if it helps.

Cheers!

**Comment by u451f** [comment]
Ok, done. I let you verify that i made no gross mistake.

**Comment by azadi** [comment]
Hi @u451f,

First up, sorry for delaying this but as you may have noticed we just resumed working on TorBirdy. 

1. Thanks for these changes. I am going to go ahead and merge them and sort out the minor issues later.
2. Please let me know who to credit for this release.

**Comment by u451f** [comment]
Dear Sukhbir, 

thanks a lot! 
as for the credit, it's work by Tails Developers tails @ boum.org.

So as soon as there's a new release, I'll package it for Debian.

Cheers!

**Pull request merged**
